version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 20
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
