site_name: HilbertSFC
site_description: Ultra-fast 2D & 3D Hilbert space-filling curve encode/decode kernels (NumPy + Numba).
repo_url: https://github.com/remcofl/HilbertSFC
repo_name: remcofl/HilbertSFC
site_url: https://remcofl.github.io/HilbertSFC/

extra:
  version:
    provider: mike
    default: latest
    alias: true

docs_dir: docs

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Advanced usage: advanced-usage.md
  - Benchmarks:
      - CPU ↗: https://github.com/remcofl/HilbertSFC/blob/main/benchmark-cpu.md
      - GPU ↗: https://github.com/remcofl/HilbertSFC/blob/main/benchmark-gpu.md
  - API Reference:
      - api/index.md
      - hilbertsfc: api/hilbertsfc.md
      - hilbertsfc.torch: api/torch.md
      - Types:
          - hilbertsfc.types: api/types/types.md
          - hilbertsfc.torch.types: api/types/torch-types.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_section_style: table
            docstring_style: numpy
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            show_overloads: false
            show_root_heading: true
            show_category_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv

markdown_extensions:
  - pymdownx.blocks.admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true
  - toc:
      permalink: true
