name: Feature request
description: Suggest an idea or enhancement.
title: "[FEAT] - "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem are you trying to solve?
      placeholder: "I want to ..., because ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: "Add/Change ..., so that ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered.
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, examples, or prior art.
    validations:
      required: false
